### ISSUE TITLE
Quest - The Klaxxi Council

### ISSUE THREAD

**Issue by Aabpaladin** [Damieninabox/Lotus-WoW-Bugtracker#44] opened 2021-12-04 07:42 UTC
**Describe the bug**
When taking a ride on Kil'Ruk the Wind Reaver you will reach a point before getting to Kil'Ruk will disappear and will leave you in the air. You will not be able to cast spells, mount or use your hearthstone. It will also give you a fatigue bar and eventually kill you. You will not become a spirit and will be able to run around with 0% health. Cannot aggro mobs, attack or use spells still. You will need to log in and out to become a spirit and will NOT be mounted on a spirit gryphon. 

Cannot complete quest by going to Klaxxi'Vess yourself. 

![WoWScrnShot_120421_013507](https://user-images.githubusercontent.com/95519949/144701816-003f5e77-ef7d-4369-a620-0ff9d02b82df.jpg)

![WoWScrnShot_120421_012116](https://user-images.githubusercontent.com/95519949/144701801-e8b97629-eae7-436f-9b50-f941b3776575.jpg)

![WoWScrnShot_120421_012110](https://user-images.githubusercontent.com/95519949/144701795-5e3b42b0-0f93-4185-b5ea-68cceaac4f66.jpg)

**To Reproduce**
Steps to reproduce the behavior: Talk to Kil'ruk and as him for a ride to Klaxxi'Vess
Location - Dread Wastes 
How it should work - Should have a nice ride without the fatigue and death.

**Comment by Damieninabox** [comment] 2021-12-04 12:31
Can not reproduce it -> ride is smooth and he drops the passenger where he is supposed to land

**Comment by Damieninabox** [comment] 2021-12-19 02:41
Still could not reproduce it, neither local nor live -> will close this one for now and check it after the next server update (just in case)

**Closed as completed by Damieninabox** 2021-12-19 02:41 UTC
