### ISSUE TITLE
Synapse Springs

### ISSUE THREAD

**Issue by Naytan96** [Damieninabox/Lotus-WoW-Bugtracker#87] opened 2021-12-05 00:34 UTC
**Describe the bug**
Synapse springs sharing a cooldown with on use trinkets (unsure if intended but wasn't the case during mop)

**To Reproduce**
use synapse springs with an on use trinket equipped

**Comment by irrefutable** [comment] 2021-12-05 14:02
Using Synapse gives the one-use trinket 10 sec CD. Using the On-use trinket gives Synapse a 20 second CD. 
Tested it with several classes and PvP-trinkets.
Working as intended unless OP is refering to a PvE trinket. Can close the issue.

**Closed as completed** 2021-12-09 22:16 UTC
