### ISSUE TITLE
Quest - Falling to Pieces

### ISSUE THREAD

**Issue by Aabpaladin** [Damieninabox/Lotus-WoW-Bugtracker#223] opened 2021-12-09 22:34 UTC
**Describe the bug**
Amber Shard next to Oracle Hiss'ir does not allow you to pick up quest ''Falling to Pieces''
Maybe caused by The Klaxxi Council being unable to be completed at this time (Doubtful)

**To Reproduce**
Steps to reproduce the behavior: Be next to Amber Shard
Location Dread Wastes - The Briny Muck

How it should work
Should be able to pick up the quest ''falling to pieces''

**Screenshots**

![WoWScrnShot_120921_163322](https://user-images.githubusercontent.com/95519949/145486389-4abb00dc-4dd4-44a0-9134-117826f071f6.jpg)

**Additional context**

**Comment by Damieninabox** [comment] 2021-12-13 22:57
Quest is available after completing 31091 "Reunited" according wowpedia storylines.

Working as intended, will close it

**Closed as completed by Damieninabox** 2021-12-13 22:57 UTC

**Comment by Aabpaladin** [comment] 2021-12-14 06:56
I have completed the quest Reunited AND the follow up quests for it and the quest does not appear even after you kill Oracle again.
