### ISSUE TITLE
Thunder hold invisible mobs

### ISSUE THREAD

**Issue by TheRealRickle** [Damieninabox/Lotus-WoW-Bugtracker#102] opened 2021-12-05 10:28 UTC
**Describe the bug**
While in thunder hold, my pet got killed by invisible mobs who, when my pet died, was visible for like half a second, called Thunder Hold Soldier.

**To Reproduce**
I just send my pet in to kill some mobs in thunder hold, sometimes the bug happens, sometimes it doesn't

Location
Thunder hold, Jade Forest

**Screenshots**
![WoWScrnShot_120521_112640](https://user-images.githubusercontent.com/41706713/144742819-0a4798f2-ac47-4534-9579-50f4c6680115.jpg)

![WoWScrnShot_120521_112723](https://user-images.githubusercontent.com/41706713/144742821-73e9df5a-94e0-4678-9505-954eeddf6509.jpg)

**Comment by TheRealRickle** [comment] 2021-12-05 10:31
Update: the mobs just targeted and killed me instead of my pet, unsure why.
![WoWScrnShot_120521_113222](https://user-images.githubusercontent.com/41706713/144742928-75f48665-7096-43a5-9c27-568221e3bdf5.jpg)

**Comment by Damieninabox** [comment] 2021-12-28 19:01
Not able to reproduce it, maybe a previous fix also managed to somehow fix this, will close it for now

**Closed as completed by Damieninabox** 2021-12-28 19:01 UTC
