### ISSUE TITLE
Quest - Skeer the Bloodseeker

### ISSUE THREAD

**Issue by Aabpaladin** [Damieninabox/Lotus-WoW-Bugtracker#220] opened 2021-12-09 20:12 UTC
**Describe the bug**
No cast time on breaking amber
Skeer does not appear after Amber is broken and thus cannot do the 3 follow up quests

**To Reproduce**
Steps to reproduce the behavior: Have the quest "Skeer the Bloodseeker" and right click his amber tomb.
Location Dread Wastes - Muckscale Grotto
How it should work
After breaking the Amber Skeer should appear so you can hand in the quest "Skeer the Bloodseeker" and then get 3 follow up quests from him while still in Muckscale Grotto

https://www.wowhead.com/quest=31175/skeer-the-bloodseeker#videos:id=123008

**Comment by Aabpaladin** [comment] 2021-12-09 22:37
Would like to also edit that is now appears in Klaxxi'vess where you can hand in the quest and get his 3 follow ups. He should still only be at Muckscale Grotto.

**Comment by Damieninabox** [comment] 2021-12-19 02:14
Couldn't reproduce on our local systems -> fixed the phasing issue, will have to recheck it again after the next server update, closing it for now

**Closed as completed by Damieninabox** 2021-12-19 02:14 UTC
